In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [8]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [11]:
#Creating a Numpy Array
my_list = [1, 2, 3, 4, 5, 6]

my_array = np.array(my_list)
print(my_array)

[1 2 3 4 5 6]


In [12]:
arr = np.array([1, 2])
print(arr)

[1 2]


In [15]:
# .dtype attribute

a = np.array([1, "A", True])
print(a.dtype)

b = np.array([1, 2, 3])
print(b.dtype)

c = np.array([1.1, 2.3])
print(c.dtype)

<U11
int32
float64


In [22]:
"""
Size Comparsion of ndarray and list object
"""

from sys import getsizeof

lst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(getsizeof(lst))


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(getsizeof(arr))

136
144


In [23]:
lst = [1, 2, 3]
arr = np.array(lst)

arr = arr ** 3
print(arr)

[ 1  8 27]


In [48]:
"""
Exercise
"""

test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

test_3_fixed = test_3 + 2

print(test_1, test_2, test_3)
print(test_3_fixed)

total_grade = test_1 + test_2 + test_3_fixed
print(total_grade)

final_grade = total_grade / 3
print(final_grade)

jeremy_test_2 = test_2[3]
print(jeremy_test_2)

manual_adwoa_test_1 = [test_1[1], test_1[2]]
print(manual_adwoa_test_1)


student_scores = np.array([test_1, test_2, test_3_fixed])
print(student_scores)

print(student_scores[2][0])

print(student_scores[:, 4])

[92 94 88 91 87] [ 79 100  86  93  91] [87 85 72 90 92]
[89 87 74 92 94]
[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]
93
[94, 88]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 89  87  74  92  94]]
89
[87 91 94]


In [56]:
"""
Logical Operations with Arrays
"""

#masking
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mask = lst > 5
print(mask)


# select using Logical operations
selected = arr[(arr < 5) | (arr > 3)]
print(selected)

#comvined Logical operations

[False False False False False  True  True  True  True  True]
[ 1  2  3  4  5  6  7  8  9 10]
