In [1]:
import numpy as np

In [7]:
"""
Numpy Array Attributes
"""

print(np.arange(3)) # stop
print(np.arange(2, 5)) # start, stop
print(np.arange(1, 9, 2)) # start, stop, step

# Creating an array

[0 1 2]
[2 3 4]
[1 3 5 7]


In [44]:
# Random number generator


arr1 = np.random.randint(99, size=5)
print(arr1)
print()

arr2 = np.random.randint(100, size=(3, 5))
print(arr2)
print()

arr3 = np.random.randint(100, size=(3, 5, 2))
print(arr3)

# np.random.seed(num):

[12 83 59 85 77]

[[47  7 40 43 21]
 [ 9 13  4 73 59]
 [12 95 62 13 72]]

[[[95 21]
  [98 94]
  [84 27]
  [34 60]
  [25 86]]

 [[ 1 27]
  [63 16]
  [99 64]
  [85  6]
  [18 44]]

 [[ 0 95]
  [ 4 47]
  [49 27]
  [55 97]
  [44 13]]]


In [59]:
# Attributes

print("arr1.ndim = ", arr1.ndim)
print("arr2.ndim = ", arr2.ndim)
print("arr2.shape = ", arr2.shape)
print("arr3.shape = ", arr3.shape)

print("arr2.size = ", arr2.size)
print("arr2.dtype = ", arr2.dtype)
print("arr2.itemsize = ", arr2.itemsize)

arr4 = np.array([1.5 , 2.3, 3.4])
print("arr4.tiemsize = ", arr4.itemsize)

print("arr2.nbytes = ", arr2.nbytes)
print("arr1.nbytes = ", arr1.nbytes)

arr1.ndim =  1
arr2.ndim =  2
arr2.shape =  (3, 5)
arr3.shape =  (3, 5, 2)
arr2.size =  15
arr2.dtype =  int32
arr2.itemsize =  4
arr4.tiemsize =  8
arr2.nbytes =  60
arr1.nbytes =  20


In [69]:
arr = np.random.randint(100, size=(6, 8))
print(arr)

print(arr[:2, :3])
print(arr[:3, ::2])


[[38 36  2 70 83 33 63 58]
 [11 99 53 23 81 76 56 91]
 [26 30 40 85  8 56 94 43]
 [77 80  6 65 12 40 76 53]
 [74 89 10 90 13 35 11  5]
 [16  8 35 94 12 41 52 78]]
[[38 36  2]
 [11 99 53]]
[[38  2 83 63]
 [11 53 81 56]
 [26 40  8 94]]


In [71]:
"""
Slicing
"""



'\nSlicing\n'

In [80]:
"""
Subarrays as no-copy views
"""
np.random.seed(1)
arr = np.random.randint(10, size=(3, 4))
print(arr, '\n')


arr_sub = arr[:2, :2]
print(arr_sub, '\n')

arr_sub[0, 0] = -1
print(arr_sub, '\n')

print(arr)

#리스트는 복사본을 만들어서 return

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]] 

[[5 8]
 [0 0]] 

[[-1  8]
 [ 0  0]] 

[[-1  8  9  5]
 [ 0  0  1  7]
 [ 6  9  2  4]]


In [81]:
# .copy()

np.random.seed(1)
arr = np.random.randint(10, size=(3, 4))
print(arr, '\n')

arr_sub = arr[:2, :2].copy()
print(arr_sub, '\n')

arr_sub[0, 0] = -1
print(arr_sub, '\n')

print(arr)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]] 

[[5 8]
 [0 0]] 

[[-1  8]
 [ 0  0]] 

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]


In [85]:
"""
Reshaping of Arrays
"""

arr = np.arange(1, 10)
print(arr, '\n')

grid = arr.reshape(3, 3)
print(grid)

[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [90]:
# np.newaxis

arr = np.array([1, 2, 3])
print(arr)
print("arr.ndim = ", arr.ndim)
print("arr.shape = ", arr.shape, '\n')

arr_new = arr[np.newaxis, :]
print("arr_new.ndim = ", arr_new.ndim)
print("arr_new.shape = ", arr_new.shape, '\n')

arr_new = arr[np.newaxis, :]
print("arr_new.ndim = ", arr_new.ndim)
print("arr_new.shape = ", arr_new.shape, '\n')

arr_new2 = arr[:, np.newaxis]
print("arr_new2.ndim = ", arr_new2.ndim)
print("arr_new2.shape = ", arr_new2.shape, '\n')


[1 2 3]
arr.ndim =  1
arr.shape =  (3,) 

arr_new.ndim =  2
arr_new.shape =  (1, 3) 

arr_new.ndim =  2
arr_new.shape =  (1, 3) 

arr_new2.ndim =  2
arr_new2.shape =  (3, 1) 



In [96]:
"""
Array Concatenation
"""

arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])
arr_3 = np.array([7, 8, 9])

arr_total = np.concatenate([arr_1, arr_2, arr_3])
print(arr_total)


arr_total = np.vstack([arr_1, arr_2, arr_3])
print(arr_total)




[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [106]:
"""
Array Splitting
"""

arr = [1, 2, 3, 99, 99, 3, 2, 1]
print(arr)

arr_1, arr_2, arr_3 = np.split(arr, [3, 5])
print(arr_1, arr_2, arr_3)


arr_1, arr_2 = np.split(arr, [4])
print(arr_1, arr_2)


[1, 2, 3, 99, 99, 3, 2, 1]
[1 2 3] [99 99] [3 2 1]
[ 1  2  3 99] [99  3  2  1]
