In [23]:
import pandas as pd

In [24]:
pd.__version__

'1.2.4'

In [25]:
ser = pd.Series([0.25, 0.2, 0.75, 1.0]) # constructor method: 객체를 생성하는 매서드
print(ser)
print(ser.shape)


print(ser.values)
print(type(ser.values))

0    0.25
1    0.20
2    0.75
3    1.00
dtype: float64
(4,)
[0.25 0.2  0.75 1.  ]
<class 'numpy.ndarray'>


In [31]:
ser = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
print(ser)

print(ser['b']) #명시적
print(ser[1]) #암묵적

dict = 

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
0.5
0.5


In [35]:
dict = {'a': 1, 2: 'two', 'third': True} #dict{key1:value1}
print(dict)

print(dict['a'])

{'a': 1, 2: 'two', 'third': True}
1


In [41]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   "New York": 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}


population = pd.Series(population_dict)
print(population)
print()
print(population['California':'New York'])
print()
print(population[:4])

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

California    38332521
Texas         26448193
New York      19651127
dtype: int64

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64


In [43]:
area_dict = {'California': 423967,'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}

area = pd.Series(area_dict)
print(area)

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64


In [86]:
df = pd.DataFrame({'population': population, 'area': area})

print(df)
print()

print(df.index)
print()

print(df.columns)
print()

area = df['area']
print(area)

            population      area
California    38332521  38332521
Texas         26448193  26448193
New York      19651127  19651127
Florida       19552860  19552860
Illinois      12882135  12882135

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

Index(['population', 'area'], dtype='object')

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: area, dtype: int64


In [58]:
import numpy as np

In [77]:
arr = np.random.rand(3, 2)
print(arr)

df2 = pd.DataFrame(arr, columns=['foo', 'bar'], index=['2021-10-13', '2021-10-14', '2021-10-15'])
print(df)

[[0.28514529 0.12735715]
 [0.93856321 0.13731765]
 [0.14451429 0.10101089]]
                 foo       bar
2021-10-13  0.526059  0.810370
2021-10-14  0.421867  0.088055
2021-10-15  0.369776  0.831861


In [71]:
dict = {'a': 1, 2: 'two', 'third': True} #dict{key1:value1}

'a' in dict
print('two' in dict)

False


In [75]:
ser = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])

print(ser['b'])
'a' in ser
0.25 in ser  #key 검색만 가능 value는 불가능



0.5


False

In [87]:
print(df)

df['density'] = df['population']/df['area']
print(df)

            population      area
California    38332521  38332521
Texas         26448193  26448193
New York      19651127  19651127
Florida       19552860  19552860
Illinois      12882135  12882135
            population      area  density
California    38332521  38332521      1.0
Texas         26448193  26448193      1.0
New York      19651127  19651127      1.0
Florida       19552860  19552860      1.0
Illinois      12882135  12882135      1.0


In [105]:
print(df.loc['New York':'Illinois']) #명시적 인덱스
print() 
print(df.iloc[2:5]) #암묵적 인덱스 정수기반

          population      area  density
New York    19651127  19651127      1.0
Florida     19552860  19552860      1.0
Illinois    12882135  12882135      1.0

          population      area  density
New York    19651127  19651127      1.0
Florida     19552860  19552860      1.0
Illinois    12882135  12882135      1.0


In [109]:
print(df.values, '\n')
print(df.T, '\n')

print(df.iloc[:3,:2],' \n')
print(df.density)

[[3.8332521e+07 3.8332521e+07 1.0000000e+00]
 [2.6448193e+07 2.6448193e+07 1.0000000e+00]
 [1.9651127e+07 1.9651127e+07 1.0000000e+00]
 [1.9552860e+07 1.9552860e+07 1.0000000e+00]
 [1.2882135e+07 1.2882135e+07 1.0000000e+00]] 

            California       Texas    New York     Florida    Illinois
population  38332521.0  26448193.0  19651127.0  19552860.0  12882135.0
area        38332521.0  26448193.0  19651127.0  19552860.0  12882135.0
density            1.0         1.0         1.0         1.0         1.0 

            population      area
California    38332521  38332521
Texas         26448193  26448193
New York      19651127  19651127  

California    1.0
Texas         1.0
New York      1.0
Florida       1.0
Illinois      1.0
Name: density, dtype: float64
